apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: rodobkn/multi-server
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379' # In the env variables you need to provide only strings
            - name: PGUSER
              value: postgres # This is the default postgres user, and is not the best way to do the things according to Stephen
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432' # In the env variables you need to provide only strings
            - name: PGDATABASE
              value: postgres # This is the default postgres database, and is not the best way to do the things according to Stephen
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword # name of the secret object
                  key: PGPASSWORD # the key stored inside the secret object

